apiVersion: extensions/v1
kind: Deployment
metadata:
  name: say-deployment
  labels:
    app: say
spec:
  replicas: 3
  selector:
    matchLabels:
      app: say
  template:
    metadata:
      labels:
        app: say
    spec:
      containers:
        - name: say
          image: taraktikos/say
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: say-service
spec:
  selector:
    app: say
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
